### ISSUE TITLE
Make it possible to use staging for developing the workflow

### ISSUE THREAD

**Issue by ba-encodify** [dextercai/lego-action#1]
Right now if you run lego for same domain name to many times it blocks you
Make it possible to set server to  https://acme-staging-v02.api.letsencrypt.org/directory or similar for testing the workflow

**Comment by dextercai** [comment]
You could use `lego-server` parameter in action version `v1.1-beta`. 
Please note that in order to use different ACME servers, you may need to update `LEGO_ACCOUNT_TAR` in advance

**Comment by ba-encodify** [comment]
Any idea when the beta get release fully?

**Comment by dextercai** [comment]
Actually, there is no actual difference between the beta and final release of this project. 
I have already used this set of actions in my production scenario. :)
I can release it, and hoping to get some practical feedback on its use.
